#include <windows.ui.xaml.h>
#include <dxgi1_6.h>
#include <Robuffer.h>

extern "C" const IID IID___x_ABI_CWindows_CUI_CXaml_CIApplicationStatics = __uuidof(__x_ABI_CWindows_CUI_CXaml_CIApplicationStatics),

IID___x_ABI_CWindows_CUI_CXaml_CIApplicationOverrides = __uuidof(__x_ABI_CWindows_CUI_CXaml_CIApplicationOverrides),
IID___x_ABI_CWindows_CUI_CXaml_CIApplicationInitializationCallback = __uuidof(__x_ABI_CWindows_CUI_CXaml_CIApplicationInitializationCallback),
IID___x_ABI_CWindows_CUI_CXaml_CIApplicationFactory = __uuidof(__x_ABI_CWindows_CUI_CXaml_CIApplicationFactory),
IID___x_ABI_CWindows_CUI_CPopups_CIMessageDialog = __uuidof(__x_ABI_CWindows_CUI_CPopups_CIMessageDialog),
IID___x_ABI_CWindows_CUI_CPopups_CIMessageDialogFactory = __uuidof(__x_ABI_CWindows_CUI_CPopups_CIMessageDialogFactory),
IID___x_ABI_CWindows_CApplicationModel_CCore_CIFrameworkView = __uuidof(__x_ABI_CWindows_CApplicationModel_CCore_CIFrameworkView),
IID___x_ABI_CWindows_CApplicationModel_CCore_CIFrameworkViewSource = __uuidof(__x_ABI_CWindows_CApplicationModel_CCore_CIFrameworkViewSource),
IID___x_ABI_CWindows_CApplicationModel_CCore_CICoreApplication = __uuidof(__x_ABI_CWindows_CApplicationModel_CCore_CICoreApplication),
IID___x_ABI_CWindows_CApplicationModel_CCore_CICoreApplicationExit = __uuidof(__x_ABI_CWindows_CApplicationModel_CCore_CICoreApplicationExit),
IID_IDXGIFactory7 = __uuidof(IDXGIFactory7),
IID___x_ABI_CWindows_CUI_CCore_CICoreWindowStatic = __uuidof(__x_ABI_CWindows_CUI_CCore_CICoreWindowStatic),
IID_IBufferByteAccess = __uuidof(Windows::Storage::Streams::IBufferByteAccess),
IID___x_ABI_CWindows_CStorage_CIFileIOStatics = __uuidof(__x_ABI_CWindows_CStorage_CIFileIOStatics),
IID___x_ABI_CWindows_CApplicationModel_CIPackage = __uuidof(__x_ABI_CWindows_CApplicationModel_CIPackage),
IID___x_ABI_CWindows_CApplicationModel_CIPackageStatics = __uuidof(__x_ABI_CWindows_CApplicationModel_CIPackageStatics),
IID___FIAsyncOperationCompletedHandler_1_Windows__CStorage__CStreams__CIBuffer = __uuidof(__FIAsyncOperationCompletedHandler_1_Windows__CStorage__CStreams__CIBuffer),
IID___FIAsyncOperation_1_Windows__CStorage__CStreams__CIBuffer = __uuidof(__FIAsyncOperation_1_Windows__CStorage__CStreams__CIBuffer),
IID___x_ABI_CWindows_CStorage_CIStorageFolder = __uuidof(__x_ABI_CWindows_CStorage_CIStorageFolder);

#define GEN_IID_FROM_STRING(string, iname) MIDL_INTERFACE(string) iname; \
extern "C" const IID IID_##iname = __uuidof(iname);

GEN_IID_FROM_STRING("9FD96657-5294-5A65-A1DB-4FEA143597DA", __x_Microsoft_CUI_CXaml_CIApplicationFactory)

GEN_IID_FROM_STRING("3785B209-37BB-5B49-B3C6-6974DCDC4787", __x_Microsoft_CUI_CXaml_CIApplicationOverrides)

GEN_IID_FROM_STRING("4E0D09F5-4358-512C-A987-503B52848E95", __x_Microsoft_CUI_CXaml_CIApplicationStatics)

GEN_IID_FROM_STRING("D8EEF1C9-1234-56F1-9963-45DD9C80A661", __x_Microsoft_CUI_CXaml_CIApplicationInitializationCallback)

GEN_IID_FROM_STRING("d0d50509-6092-42b7-a33c-7db25ba2527e", mainframe)
GEN_IID_FROM_STRING("3cd2ad98-88a7-41ab-ad5b-64d7a9a219aa", mainpage)

GEN_IID_FROM_STRING("64BD43F8-BFEE-4EC4-B7EB-2935158DAE21", unknownforreal)

GEN_IID_FROM_STRING("629BDBC8-D932-4FF4-96B9-8D96C5C1E858", __x_ABI_CWindows_CFoundation_CIPropertyValueStatics)

GEN_IID_FROM_STRING("53A3070F-19D9-59BC-BDD6-4DBF139E7DA5", __x_Microsoft_CUI_CXaml_CControls_CIFrameFactory)

GEN_IID_FROM_STRING("44A9796F-723E-4FDF-A218-033E75B0C084", __x_ABI_CWindows_CFoundation_CIUriRuntimeClassFactory)

GEN_IID_FROM_STRING("2D7EB3FD-ECDB-5084-B7E0-12F9598381EF", __x_Microsoft_CUI_CXaml_CXamlTypeInfo_CIXamlControlsXamlMetaDataProviderStatics)

GEN_IID_FROM_STRING("A96251F0-2214-5D53-8746-CE99A2593CD7", __x_Microsoft_CUI_CXaml_CMarkup_CIXamlMetadataProvider)

GEN_IID_FROM_STRING("9B8445F7-D938-5626-850A-86E91CA89E98", __x_Microsoft_CUI_CXaml_CControls_CIPageOverrides)

GEN_IID_FROM_STRING("FF4357D5-DDCD-5129-9D0F-D8AED2ADC1A9", __x_Microsoft_CUI_CXaml_CControls_CIPageFactory)

GEN_IID_FROM_STRING("D24219DF-7EC9-57F1-A27B-6AF251D9C5BC", __x_Microsoft_CUI_CXaml_CMarkup_CIXamlType)

GEN_IID_FROM_STRING("918CA043-F42C-5805-861B-62D6D1D0C162", __x_Microsoft_CUI_CXaml_CControls_CIXamlControlsResources)

GEN_IID_FROM_STRING("AD401812-B091-51D0-B915-2D682CD2AF10", __x_Microsoft_CUI_CXaml_CMarkup_CIComponentConnector)

GEN_IID_FROM_STRING("FB4EC2CE-3074-5C42-B655-64FB81FBD040", __x_Microsoft_CUI_CXaml_CControls_CIWebView2Factory)

GEN_IID_FROM_STRING("BF3A2913-5C63-50EC-8660-61809BE7B9B9", __x_Microsoft_CUI_CXaml_CMarkup_CIXamlMember)

GEN_IID_FROM_STRING("4BD682DD-7554-40E9-9A9B-82654EDE7E62", __x_ABI_CWindows_CFoundation_CIPropertyValue)

GEN_IID_FROM_STRING("9E365E57-48B2-4160-956F-C7385120BBFC", __x_ABI_CWindows_CFoundation_CIUriRuntimeClass)

GEN_IID_FROM_STRING("4A7EBB28-DBB2-5EE5-BAF0-1DEFB9C5B658", __x_Microsoft_CUI_CXaml_CControls_CIWebView2)

GEN_IID_FROM_STRING("EB42988E-6CB5-5DD6-9E59-4C04E5CAEC6D", __x_Microsoft_CUI_CXaml_CControls_CIPage)

GEN_IID_FROM_STRING("9BC9D617-B5F8-5AD8-80C1-93D8B82425F9", __x_Microsoft_CUI_CXaml_CIApplication)